sampler:
  _target_: l2co_tasks.PDETaskSampler
sampler_kwargs:
  seed: ${seed}

experimentdata:
  domain:
    input:
      hidden_size:
        type: category
        categories:
          - 32

task_kwargs:

data_generator:
  _target_: l2co_tasks.create_pde_task
  _partial_: True

schema:
  # Feature schema used by FeatureProcessor to encode task metadata for the model
  dimensionality: continuous
  task_name:
    - convection
    - reaction
    - wave
